extends RefCounted
## Canonical data is generated by scripts/sync_content.py.
const ROOT = "res://content/generated/"
const STATS = ["strength", "agility", "vitality", "intelligence"]
const STAT_NAMES = {"strength": "Сила", "agility": "Ловкость", "vitality": "Живучесть", "intelligence": "Интеллект"}
const SLOTS = ["weapon", "shield", "body", "feet", "ring", "amulet"]
var items: Array = []
var skills: Array = []
var creatures: Array = []
var portraits: Array = []
var maps: Array = []
var encounters: Array = []
var story: Dictionary
var characters: Array = []
var map_points: Dictionary
var journey_rules: Dictionary
var portrait_presentation: Dictionary
var base: Array = []
var balance: Dictionary
var palette: Dictionary
var art: Dictionary

func _init():
	for name in ["weapons", "shields", "armor", "footwear", "jewelry", "basic-equipment"]:
		items.append_array(read_json(name))
	skills = read_json("skills")
	creatures = read_json("creatures")
	portraits = read_json("hero-portraits")
	maps = read_json("maps")
	encounters = read_json("journey-encounters")
	base = read_json("base-actions")
	for equipment in items:
		if equipment.has("baseFigureAvailability"):
			equipment.figures = base.filter(func(figure): return figure.get("availability", "") == equipment.baseFigureAvailability).duplicate(true)
	balance = read_json("combat-balance")
	palette = read_json("palette")
	art = read_json("item-art")
	story = read_json("story-runtime")
	characters = read_json("characters")
	map_points = read_json("map-points")
	journey_rules = read_json("journey-rules")
	portrait_presentation = read_json("portrait-presentation")

func stat_abbreviation(stat: String) -> String:
	return str(STAT_NAMES.get(stat, stat)).left(3).to_upper()

func read_json(name: String):
	return JSON.parse_string(FileAccess.get_file_as_string(ROOT + name + ".json"))

func lookup(entries: Array, id: String) -> Dictionary:
	for entry in entries:
		if entry.id == id: return entry
	return {}

func encounter_variant(expedition: int, stage: int) -> String:
	for rule in encounters:
		# JSON numbers are floats; Array.has() distinguishes them from integer stages.
		if int(rule.expedition) == expedition and rule.stages.any(func(s): return int(s) == stage): return rule.creatureVariant
	return ""

func creature_pool(expedition: int, variant: String = "") -> Array:
	return creatures.filter(func(c): return c.encounter.combat and c.encounter.minExpedition <= expedition and (variant.is_empty() or c.get("variants", {}).has(variant)))

func creature_variant_error(f: Dictionary) -> String:
	if not f.get("creatureVariant", ""): return ""
	var species = lookup(creatures, f.get("creatureId", ""))
	if not species.get("variants", {}).has(f.creatureVariant):
		return "Неизвестный вариант существа: %s (%s)" % [f.creatureVariant, f.get("creatureId", "")]
	return ""

func creature_figures(f: Dictionary) -> Array:
	var error = creature_variant_error(f)
	if error:
		push_error(error)
		return []
	var species = lookup(creatures, f.get("creatureId", ""))
	if species.is_empty(): return []
	return species.variants[f.creatureVariant].figures if f.get("creatureVariant", "") else species.figures

func item(reference) -> Dictionary:
	var parts = str(reference if reference else unarmed().id).split("@")
	var template = lookup(items, parts[0])
	if template.is_empty():
		push_error("Неизвестный предмет: " + str(reference))
		return {}
	var scales = template.get("defenseScalesWithLevel", false)
	for figure in template.figures:
		if not figure.get("healthDamage", {}).get("stats", []).is_empty(): scales = true
	var rank = clampi(int(parts[1]) if parts.size() > 1 else 1, 1, 999) if scales and not template.get("unarmed", false) else 1
	var result = template.duplicate(true)
	result.templateId = template.id
	result.level = rank
	result.id = template.id + ("@%d" % rank if rank > 1 else "")
	for stat in result.requirements: result.requirements[stat] = rank
	if template.get("defenseScalesWithLevel", false):
		for type in result.get("defense", {}): result.defense[type] *= rank
	return result

func permits(f: Dictionary, equipment: Dictionary) -> bool:
	if not f.get("creatureId", ""): return true
	var species = lookup(creatures, f.creatureId)
	return not species.is_empty() and equipment.slot in species.equipment.slots and (not species.equipment.has("allowedItems") or equipment.templateId in species.equipment.allowedItems)

func can_use(f: Dictionary, equipment: Dictionary) -> bool:
	if not permits(f, equipment): return false
	for stat in STATS:
		if effective_stat(f, stat) < equipment.requirements.get(stat, 0): return false
	return true

func wear(f: Dictionary, equipment: Dictionary, include_basics: bool = true) -> bool:
	if not can_use(f, equipment): return false
	if equipment.get("hands", 1) == 2: f.gear.shield = null
	if equipment.kind == "shield" and item(f.gear.weapon).get("hands", 1) == 2: f.gear.weapon = null
	f.gear[equipment.slot] = equipment.id
	if include_basics: equip_basics(f)
	return true

func has_equipment(f: Dictionary, slot: String) -> bool:
	if not f.gear.get(slot): return false
	return not item(f.gear[slot]).get("unarmed", false)

func basic_item(slot: String) -> Dictionary:
	for equipment in items:
		if equipment.get("unarmed", false) and equipment.slot == slot: return equipment
	return {}

func equip_basics(f: Dictionary):
	if f.get("creatureId", ""): return
	for equipment in items:
		if not equipment.get("unarmed", false) or f.gear.get(equipment.slot): continue
		if equipment.slot == "shield" and item(f.gear.get("weapon")).get("hands", 1) == 2: continue
		f.gear[equipment.slot] = equipment.id

func max_hp(f: Dictionary) -> float:
	return balance.health.base + balance.health.perVitality * (effective_stat(f, "vitality") - 1)

func stat_total(f: Dictionary) -> int:
	var total = 0
	for stat in STATS: total += int(f.stats[stat])
	return total

func level(f: Dictionary) -> int:
	return maxi(0, stat_total(f) - 6)

func color(token: String) -> Color:
	var value = palette.get("color-" + token, "#ffffff")
	return Color.TRANSPARENT if value == "transparent" else Color(value)

func image(path: String) -> Texture2D:
	var full = ROOT + "art" + path
	return load(full) if not path.is_empty() and ResourceLoader.exists(full) else null

func portrait(f: Dictionary) -> Texture2D:
	if f.get("characterId", ""):
		return image(lookup(characters, f.characterId).get("portrait", {}).get("src", ""))
	if f.get("creatureId", ""):
		return image(lookup(creatures, f.creatureId).get("portrait", {}).get("src", ""))
	var portrait_id = str(f.get("portraitId", "")).replace("character-", "hero-")
	var selected = lookup(portraits, portrait_id)
	if selected.is_empty() and not portraits.is_empty(): selected = portraits[0]
	return image(selected.get("src", ""))

func framed_portrait(texture: Texture2D) -> Texture2D:
	if texture == null or texture.get_width() != texture.get_height(): return texture
	var crop: Dictionary = portrait_presentation.rectangle.squareCrop
	var framed = AtlasTexture.new()
	framed.atlas = texture
	var side = float(texture.get_width())
	framed.region = Rect2(crop.x * side, crop.y * side, crop.width * side, crop.height * side)
	return framed

func unarmed() -> Dictionary:
	var equipment = basic_item("weapon")
	if not equipment.is_empty(): return equipment
	assert(false, "В каталоге не задано оружие без экипировки")
	return {}

func map_point(id: String) -> Dictionary:
	return lookup(map_points.points, id)

func point_for_node(node: Dictionary) -> Dictionary:
	return map_point(node.get("mapPointType", ""))

func speaker(id: String, player: Dictionary) -> Dictionary:
	var binding: Dictionary = story.speakers.get(id, {})
	var person = lookup(characters, binding.get("characterId", ""))
	if person.get("portraitSource", "") == "player":
		return {"name": player.name, "texture": portrait(player), "side": person.dialogueSide}
	if not person.is_empty():
		return {"name": binding.get("name", person.name), "texture": image(person.get("portrait", {}).get("src", "")), "side": person.dialogueSide}
	var creature = lookup(creatures, binding.get("portrait", {}).get("id", ""))
	return {"name": binding.get("name", ""), "texture": image(creature.get("dialoguePortrait", creature.get("portrait", {})).get("src", "")), "side": binding.get("portraitSide", "right")}

## Permanent attributes remain the basis of level/upgrade prices. Skill bonuses
## are evaluated from their IDs, never baked into saves or applied again on load.
func effective_stat(f: Dictionary, stat: String) -> int:
	var value = int(f.stats[stat])
	for definition in skills:
		if definition.id in f.get("skills", []): value += int(definition.get("passive", {}).get("statBonuses", {}).get(stat, 0))
	return value

func max_stamina(f: Dictionary) -> float:
	var value = float(balance.stamina.max)
	for definition in skills:
		if definition.id in f.get("skills", []): value += float(definition.get("passive", {}).get("maxStaminaBonus", 0))
	return value

func turn_order(f: Dictionary) -> String:
	for definition in skills:
		if definition.id in f.get("skills", []) and definition.get("passive", {}).has("turnOrder"):
			return definition.passive.turnOrder
	return ""

func conflicting_skill_slot(f: Dictionary, id: String) -> int:
	var group = lookup(skills, id).get("exclusiveGroup", "")
	if group.is_empty(): return -1
	for i in f.get("skills", []).size():
		var known = f.skills[i]
		if known != id and lookup(skills, known).get("exclusiveGroup", "") == group: return i
	return -1

func learn_skill(f: Dictionary, id: String, slot: int = -1) -> String:
	if lookup(skills, id).is_empty(): return "Неизвестный навык."
	if id in f.get("skills", []): return "Навык уже изучен."
	var conflict = conflicting_skill_slot(f, id)
	if conflict >= 0:
		if slot >= 0 and slot != conflict: return "Замените несовместимый навык в его ячейке."
		slot = conflict
	var current = f.get("skills", []).duplicate()
	if slot >= 0:
		if slot > current.size() or slot >= 3: return "Выберите доступную ячейку навыка."
		if slot == current.size(): current.append(id)
		else: current[slot] = id
	else:
		if current.size() >= 3: return "Выберите навык для замены."
		current.append(id)
	f.skills = current
	# Learning does not heal. Losing a bonus clamps resources to the new maximum.
	f.hp = minf(f.hp, max_hp(f))
	f.stamina = minf(f.stamina, max_stamina(f))
	return ""
