extends RefCounted
## Canonical data is generated by scripts/sync_content.py.
const ROOT = "res://content/generated/"
const STATS = ["strength", "agility", "vitality", "intelligence"]
const STAT_NAMES = {"strength": "Сила", "agility": "Ловкость", "vitality": "Живучесть", "intelligence": "Интеллект"}
const SLOTS = ["weapon", "shield", "body", "feet", "ring", "amulet"]
var items: Array = []
var skills: Array = []
var creatures: Array = []
var portraits: Array = []
var maps: Array = []
var encounters: Array = []
var base: Array = []
var balance: Dictionary
var palette: Dictionary
var art: Dictionary

func _init():
	for name in ["weapons", "armor", "jewelry"]:
		items.append_array(read_json(name))
	skills = read_json("skills")
	creatures = read_json("creatures")
	portraits = read_json("portraits")
	maps = read_json("journey-maps")
	encounters = read_json("journey-encounters")
	base = read_json("base-figures")
	balance = read_json("combat-balance")
	palette = read_json("palette")
	art = read_json("item-art")

func read_json(name: String):
	return JSON.parse_string(FileAccess.get_file_as_string(ROOT + name + ".json"))

func lookup(entries: Array, id: String) -> Dictionary:
	for entry in entries:
		if entry.id == id: return entry
	return {}

func encounter_variant(expedition: int, stage: int) -> String:
	for rule in encounters:
		# JSON numbers are floats; Array.has() distinguishes them from integer stages.
		if int(rule.expedition) == expedition and rule.stages.any(func(s): return int(s) == stage): return rule.creatureVariant
	return ""

func creature_pool(expedition: int, variant: String = "") -> Array:
	return creatures.filter(func(c): return c.encounter.combat and c.encounter.minExpedition <= expedition and (variant.is_empty() or c.get("variants", {}).has(variant)))

func creature_variant_error(f: Dictionary) -> String:
	if not f.get("creatureVariant", ""): return ""
	var species = lookup(creatures, f.get("creatureId", ""))
	if not species.get("variants", {}).has(f.creatureVariant):
		return "Неизвестный вариант существа: %s (%s)" % [f.creatureVariant, f.get("creatureId", "")]
	return ""

func creature_figures(f: Dictionary) -> Array:
	var error = creature_variant_error(f)
	if error:
		push_error(error)
		return []
	var species = lookup(creatures, f.get("creatureId", ""))
	if species.is_empty(): return []
	return species.variants[f.creatureVariant].figures if f.get("creatureVariant", "") else species.figures

func item(reference) -> Dictionary:
	var parts = str(reference if reference else items[0].id).split("@")
	var template = lookup(items, parts[0])
	if template.is_empty(): template = items[0]
	var scales = false
	for figure in template.figures:
		if not figure.get("healthDamage", {}).get("stats", []).is_empty(): scales = true
	var rank = clampi(int(parts[1]) if parts.size() > 1 else 1, 1, 999) if scales and not template.get("unarmed", false) else 1
	var result = template.duplicate(true)
	result.templateId = template.id
	result.level = rank
	result.id = template.id + ("@%d" % rank if rank > 1 else "")
	for stat in result.requirements: result.requirements[stat] = rank
	return result

func permits(f: Dictionary, equipment: Dictionary) -> bool:
	if not f.get("creatureId", ""): return true
	var species = lookup(creatures, f.creatureId)
	return not species.is_empty() and equipment.slot in species.equipment.slots and (not species.equipment.has("allowedItems") or equipment.templateId in species.equipment.allowedItems)

func can_use(f: Dictionary, equipment: Dictionary) -> bool:
	if not permits(f, equipment): return false
	for stat in STATS:
		if f.stats[stat] < equipment.requirements.get(stat, 0): return false
	return true

func wear(f: Dictionary, equipment: Dictionary) -> bool:
	if not can_use(f, equipment): return false
	if equipment.get("hands", 1) == 2: f.gear.shield = null
	if equipment.kind == "shield" and item(f.gear.weapon).get("hands", 1) == 2: f.gear.weapon = null
	if not equipment.get("unarmed", false): f.gear[equipment.slot] = equipment.id
	return true

func max_hp(f: Dictionary) -> float:
	return balance.health.base + balance.health.perVitality * (f.stats.vitality - 1)

func stat_total(f: Dictionary) -> int:
	var total = 0
	for stat in STATS: total += int(f.stats[stat])
	return total

func level(f: Dictionary) -> int:
	return maxi(0, stat_total(f) - 6)

func color(token: String) -> Color:
	var value = palette.get("color-" + token, "#ffffff")
	return Color.TRANSPARENT if value == "transparent" else Color(value)

func image(path: String) -> Texture2D:
	var full = ROOT + "art" + path
	return load(full) if not path.is_empty() and ResourceLoader.exists(full) else null

func portrait(f: Dictionary) -> Texture2D:
	if f.get("creatureId", ""):
		return image(lookup(creatures, f.creatureId).get("portrait", {}).get("src", ""))
	return image(lookup(portraits, f.get("portraitId", "")).get("src", ""))
